### ISSUE TITLE
null pointer reference when creating a vlan

### ISSUE THREAD

**Issue by mgaruccio** [cohesity/management-sdk-python#6]
When attempting to run the [create vlan](https://developer.cohesity.com/apidocs.html#/python/api-endpoints/vlan/create-vlan) function I get a nil pointer dereference error. the full error text is below.  The function doesn't take any input so I'm not sure what I would need to provide.

```
ERROR:cohesity_management_sdk.controllers.vlan_controller:Response status code: 500, Response message: runtime error: invalid memory address or nil pointer dereference.
 Stack trace: goroutine 93972 [running]:
cohesity/util/utils/misc.GetRuntimeStackTrace(0x1000, 0xc422695800, 0x40, 0xc4234464c8)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/util/utils/misc/misc.go:249 +0x75
cohesity/iris/server/services/web/interceptors.PanicHandler.func1.1(0xc4227e1b00, 0x7f2749e567b8, 0xc421b4d7c0)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/interceptors/interceptors.go:176 +0x149
panic(0x11fd740, 0xc4200100b0)
        /home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/runtime/panic.go:458 +0x243
cohesity/iris/server/validations.(*VlanValidator).ValidateUpdateVlanOp(0xc42284dba0, 0xc421d12120, 0xc42044b000, 0xc42284dba0, 0x1)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/validations/vlan_validator.go:205 +0x149
cohesity/iris/server/ops/public/vlan.(*UpdateVlanOp).Validate(0xc4226954c0, 0x2)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/ops/public/vlan/update_vlan_op.go:105 +0x4a6
cohesity/iris/server/baseops.ExecuteConfigUpdateOp(0x1c0db20, 0xc4226954c0, 0xc4227e1b00)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/baseops/config_base_op.go:48 +0x6e
cohesity/iris/server/services/rest/public.CreateVlan(0xc42044b000, 0xc4227e1b00, 0xc422849da0, 0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40, 0x109d401)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/rest/public/vlan_controller.go:248 +0x239
cohesity/iris/server/services/rest/base.(*RestHandler).WrapperHandler(0xc4207fcb40, 0xc42044b000, 0xc4227e1b00, 0xc422849da0, 0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/rest/base/base_rest_handler.go:197 +0x2a2
cohesity/iris/server/services/rest/base.(*RestHandler).WrapperHandler-fm(0xc42044b000, 0xc4227e1b00, 0xc422849da0, 0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/webserver.go:185 +0x66
reflect.Value.call(0x11f8340, 0xc4208bdcc0, 0x13, 0x142379d, 0x4, 0xc422258b00, 0x5, 0x5, 0x18, 0x11f8340, ...)
        /home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x11f8340, 0xc4208bdcc0, 0x13, 0xc422258b00, 0x5, 0x5, 0xc420472000, 0xc422732b40, 0x2500000000000002)
        /home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/reflect/value.go:302 +0xa4
github.com/codegangsta/inject.(*injector).Invoke(0xc421b4d720, 0x11f8340, 0xc4208bdcc0, 0xde7ad7, 0x11e12a0, 0xc4228497a0, 0xc423447ae0, 0xc423447af0)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-inject/src/github.com/codegangsta/inject/inject.go:102 +0x335
github.com/go-martini/martini.(*context).Invoke(0xc423323130, 0x11f8340, 0xc4208bdcc0, 0x16, 0xc423447b50, 0xa95305, 0xc421b4d720, 0x13367e0)
        <autogenerated>:29 +0x61
github.com/go-martini/martini.(*routeContext).run(0xc422849dd0)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:350 +0x71
github.com/go-martini/martini.(*route).Handle(0xc42132ec80, 0x7f2749e56728, 0xc423323130, 0x7f2749e567b8, 0xc421b4d7c0)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:229 +0x10f
github.com/go-martini/martini.(*router).Handle(0xc4207dc550, 0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40, 0x7f2749e56728, 0xc423323130)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:112 +0x2af
github.com/go-martini/martini.(Router).Handle-fm(0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40, 0x7f2749e56728, 0xc423323130)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/webserver.go:1160 +0x61
reflect.Value.c
Traceback (most recent call last):
  File "C:\Users\mike.garuccio\.virtualenvs\cohesity-automation-7hK7Qi6v\lib\site-packages\cohesity_management_sdk\controllers\vlan_controller.py", line 243, in create_vlan
    self.validate_response(_context)
  File "C:\Users\mike.garuccio\.virtualenvs\cohesity-automation-7hK7Qi6v\lib\site-packages\cohesity_management_sdk\controllers\base_controller.py", line 106, in validate_response
    raise raise_except
cohesity_management_sdk.exceptions.api_exception.APIException: Response status code: 500, Response message: runtime error: invalid memory address or nil pointer dereference.
 Stack trace: goroutine 93972 [running]:
cohesity/util/utils/misc.GetRuntimeStackTrace(0x1000, 0xc422695800, 0x40, 0xc4234464c8)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/util/utils/misc/misc.go:249 +0x75
cohesity/iris/server/services/web/interceptors.PanicHandler.func1.1(0xc4227e1b00, 0x7f2749e567b8, 0xc421b4d7c0)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/interceptors/interceptors.go:176 +0x149
panic(0x11fd740, 0xc4200100b0)
        /home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/runtime/panic.go:458 +0x243
cohesity/iris/server/validations.(*VlanValidator).ValidateUpdateVlanOp(0xc42284dba0, 0xc421d12120, 0xc42044b000, 0xc42284dba0, 0x1)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/validations/vlan_validator.go:205 +0x149
cohesity/iris/server/ops/public/vlan.(*UpdateVlanOp).Validate(0xc4226954c0, 0x2)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/ops/public/vlan/update_vlan_op.go:105 +0x4a6
cohesity/iris/server/baseops.ExecuteConfigUpdateOp(0x1c0db20, 0xc4226954c0, 0xc4227e1b00)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/baseops/config_base_op.go:48 +0x6e
cohesity/iris/server/services/rest/public.CreateVlan(0xc42044b000, 0xc4227e1b00, 0xc422849da0, 0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40, 0x109d401)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/rest/public/vlan_controller.go:248 +0x239
cohesity/iris/server/services/rest/base.(*RestHandler).WrapperHandler(0xc4207fcb40, 0xc42044b000, 0xc4227e1b00, 0xc422849da0, 0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/rest/base/base_rest_handler.go:197 +0x2a2
cohesity/iris/server/services/rest/base.(*RestHandler).WrapperHandler-fm(0xc42044b000, 0xc4227e1b00, 0xc422849da0, 0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/webserver.go:185 +0x66
reflect.Value.call(0x11f8340, 0xc4208bdcc0, 0x13, 0x142379d, 0x4, 0xc422258b00, 0x5, 0x5, 0x18, 0x11f8340, ...)
        /home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x11f8340, 0xc4208bdcc0, 0x13, 0xc422258b00, 0x5, 0x5, 0xc420472000, 0xc422732b40, 0x2500000000000002)
        /home/cohesity/software/toolchain/x86_64-linux/go-1.7/src/reflect/value.go:302 +0xa4
github.com/codegangsta/inject.(*injector).Invoke(0xc421b4d720, 0x11f8340, 0xc4208bdcc0, 0xde7ad7, 0x11e12a0, 0xc4228497a0, 0xc423447ae0, 0xc423447af0)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-inject/src/github.com/codegangsta/inject/inject.go:102 +0x335
github.com/go-martini/martini.(*context).Invoke(0xc423323130, 0x11f8340, 0xc4208bdcc0, 0x16, 0xc423447b50, 0xa95305, 0xc421b4d720, 0x13367e0)
        <autogenerated>:29 +0x61
github.com/go-martini/martini.(*routeContext).run(0xc422849dd0)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:350 +0x71
github.com/go-martini/martini.(*route).Handle(0xc42132ec80, 0x7f2749e56728, 0xc423323130, 0x7f2749e567b8, 0xc421b4d7c0)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:229 +0x10f
github.com/go-martini/martini.(*router).Handle(0xc4207dc550, 0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40, 0x7f2749e56728, 0xc423323130)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/build/gobuild/toolchainlibs/go-martini/src/github.com/go-martini/martini/router.go:112 +0x2af
github.com/go-martini/martini.(Router).Handle-fm(0x7f2749e567b8, 0xc421b4d7c0, 0xc421ce3a40, 0x7f2749e56728, 0xc423323130)
        /mnt/disk1/workspace/End2End-01-Build-all-rpm-and-iso/main/.go/src/cohesity/iris/server/services/web/webserver.go:1160 +0x61
reflect.Value.c```

**Comment by ashish-cohesity** [comment]
Apologies for replying late.  May I know the payload or the python script you are using . Thanks for reporting this @mgaruccio.

**Comment by ashish-cohesity** [comment]
Deeper analysis revealed, this is broken at the API layer, we will fix this soon as it gets fixed in API. Thanks again for reporting this @mgaruccio .

**Comment by ashish-cohesity** [comment]
Thanks again for reporting this @mgaruccio , This is now fixed with latest SDK.
