### ISSUE TITLE
Error when running protection_sources.list_protection_sources()

### ISSUE THREAD

**Issue by bonkeydcow** [cohesity/management-sdk-python#70]
## 🐛 Bug Report

When executing protection_sources.list_protection_sources() on some systems we receive a 500 response with the following message:

"Only one level must be queried if no entity is specified in the arg."

(Write your answer here.)

## To Reproduce

(Write your steps here:)

1. protection_sources.list_protection_sources()
2.
3.

## Expected behavior

I expect a list of protection sources. On most systems this works fine, but we have encountered one system where we get the error.

## Actual Behavior

Error: 500
"Only one level must be queried if no entity is specified in the arg."

Traceback (most recent call last):
 File "C:\Program Files\python\lib\multiprocessing\process.py", line 315, in _bootstrap
  self.run()
 File "C:\Program Files\python\lib\multiprocessing\process.py", line 108, in run
  self._target(*self.args, **self._kwargs)
 File "C:\Program Files\python\lib\site-packages\collectors\Cohesity.py", line 223, in collect
  for ps in cohesity_client.protection_sources.list_protection_sources():
 File "C:\Program Files\python\lib\site-packages\cohesity_management_sdk\controllers\protection_sources_controller.py", line 403, in list_protection_sources
  self.validate_response(_context)
 File "C:\Program Files\python\lib\site-packages\cohesity_management_sdk\controllers\base_controller.py", line 118, in validate_response
  raise raise_except
cohesity_management_sdk.exceptions.api_exception.APIException: Response status code: 500, Response message: Only one level must be queried if no entity is specified in the arg.

(Write what happened. Add screenshots, if applicable.)

**Comment by naveena-maplelabs** [comment]
Do you face this issue in any specific cluster version?
